name: Deploy to Remote Server

on:
  push:
    branches:
      - main # 任意のブランチ名に変更可能

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
        chmod 600 private_key
    - name: Deploy to Remote Server
      run: |
        ssh remote-server 'cd pitang1965.com/public_html/pitang-note && git pull'
