name: Deploy to Remote Server

on:
  push:
    branches:
      - main # 任意のブランチ名に変更可能

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key && chmod 600 private_key
    - name: login
      run: ssh -l pitang1965 -i private_key pitang1965.com -p 10022
    - name: rsync deploy
      run: rsync -auzrv -e "ssh -i private_key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 10022" --delete ./public/* pitang1965@pitang1965.com/public_html/pitang-note/ --exclude .htaccess
